# Generated by Django 4.0.4 on 2022-05-30 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('payment_provider', models.CharField(blank=True, choices=[('T', 'paystack'), ('F', 'flutterwave')], max_length=20, null=True, verbose_name='Payment Provider')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('other_info', models.TextField()),
                ('paid', models.BooleanField(default=False)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.fee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
