# Generated by Django 3.2.10 on 2022-05-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('payment_provider', '0001_initial'),
        ('user', '0004_auto_20220516_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.fee'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.student'),
        ),
    ]
