# Generated by Django 3.2.10 on 2022-05-21 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_provider', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.user'),
            preserve_default=False,
        ),
    ]
