# Generated by Django 4.0.4 on 2022-05-22 07:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_administrator_is_verified_and_more'),
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='user.teacher'),
        ),
        migrations.CreateModel(
            name='ClassRoomAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('present', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
