# Generated by Django 4.0.4 on 2022-05-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_administrator_is_verified_and_more'),
        ('school', '0003_classroom_class_teacher_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.teacher'),
        ),
    ]
