# Generated by Django 3.2.10 on 2022-05-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_administrator_is_verified_and_more'),
        ('school', '0004_alter_classroom_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='user.Teacher'),
        ),
    ]
