# Generated by Django 3.2.10 on 2022-05-23 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_administrator_is_verified_and_more'),
        ('school', '0006_term_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomattendance',
            name='present',
        ),
        migrations.RemoveField(
            model_name='classroomattendance',
            name='student',
        ),
        migrations.AddField(
            model_name='classroomattendance',
            name='attendance_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroomattendance',
            name='students',
            field=models.ManyToManyField(to='user.Student'),
        ),
    ]
