# Generated by Django 3.2.10 on 2022-05-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220523_2013'),
        ('school', '0007_auto_20220523_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='user.Student'),
        ),
    ]
