# Generated by Django 4.0.4 on 2022-05-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_povider',
            field=models.CharField(blank=True, choices=[('EMAIL', 'email'), ('GOOGLE', 'google'), ('FACEBOOK', 'facebook'), ('TWITTER', 'twitter')], default='EMAIL', max_length=20, verbose_name='user type'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
