# Generated by Django 4.0.4 on 2022-05-13 19:03

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_auth_povider_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to=user.models.upload_to, verbose_name='image'),
        ),
    ]
