# Generated by Django 3.2.10 on 2022-05-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_administrator_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
