name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env: 
          SECRET_KEY: ${{ SECRET_KEY }}
          EMAIL_HOST_USER: ${{ EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ EMAIL_HOST_PASSWORD }}
          EMAIL_HOST_PORT: ${{ EMAIL_HOST_PORT }}
          GOOOGEL_CLIENT_ID: ${{ GOOOGEL_CLIENT_ID }}
          PAYSTACK_PUBLIC_KEY: ${{ PAYSTACK_PUBLIC_KEY }}
          PAYSTACK_PRIVATE_KEY: ${{ PAYSTACK_PRIVATE_KEY }}
          FLUTTERWAVE_PUBLIC_KEY: ${{ FLUTTERWAVE_PUBLIC_KEY }}
          FLUTTERWAVE_PRIVATE_KEY: ${{ FLUTTERWAVE_PRIVATE_KEY }}
          STRIPE_PUBLIC_KEY: ${{ STRIPE_PUBLIC_KEY }}
          STRIPE_PRIVATE_KEY: ${{ STRIPE_PRIVATE_KEY }}
          FACEBOOK_APP_ID: ${{ FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET: ${{ FACEBOOK_APP_SECRET }}
          SOCIAL_SECRET: ${{ SOCIAL_SECRET }}
          DB_PASSWORD: ${{ DB_PASSWORD }}
          DB_USER: ${{ DB_USER }}
      run: |
        python manage.py test
