name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_HOST_PORT: ${{ secrets.EMAIL_HOST_PORT }}
          GOOOGEL_CLIENT_ID: ${{ secrets.GOOOGEL_CLIENT_ID }}
          PAYSTACK_PUBLIC_KEY: ${{ secrets.PAYSTACK_PUBLIC_KEY }}
          PAYSTACK_PRIVATE_KEY: ${{ secrets.PAYSTACK_PRIVATE_KEY }}
          FLUTTERWAVE_PUBLIC_KEY: ${{ secrets.FLUTTERWAVE_PUBLIC_KEY }}
          FLUTTERWAVE_PRIVATE_KEY: ${{ secrets.FLUTTERWAVE_PRIVATE_KEY }}
          STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
          STRIPE_PRIVATE_KEY: ${{ secrets.STRIPE_PRIVATE_KEY }}
          FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
          SOCIAL_SECRET: ${{ secrets.SOCIAL_SECRET }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
          PYTHONANYWHERE_DB_PASSWORD: ${{ secrets.PYTHONANYWHERE_DB_PASSWORD }}
          PYTHONANYWHERE_DB_HOST: ${{ secrets.PYTHONANYWHERE_DB_HOST }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          FLUTTERWAVE_SECRET_HASH: ${{ secrets.FLUTTERWAVE_SECRET_HASH }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          BACKEND_BASE_URL: ${{ secrets.BACKEND_BASE_URL }}
          BACKEND_ADMIN_EMAIL: ${{ secrets.BACKEND_ADMIN_EMAIL }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          PERCENTAGE_CHARGE: ${{ secrets.PERCENTAGE_CHARGE }}

      run: |
        python manage.py test
